// This file is generated by the build system. It should not be modified as it reflects the name of the current project.
// Every BLAEngine project needs one of these, and you shouldn't make it yourself

#define BLA_PROJECT_NAME BLAEngineNative
#define __BLA_PROJECT_CHECK_MACRO__COMPARE_BLAEngineNative(x) x